#!/bin/bash

for i in 1 2 3 4 5 6 7
do
	echo "Doing $i"
	gnuplot -persist <<-EOFMarker
		set term pngcairo
		set output '$i-total.png'
		set key bottom left Left reverse
		plot 'mys0$i' u 1:2
	EOFMarker
	display "$i-total.png" &
done
