#!/bin/bash

for i in 1 2 3 4 5 6 7
do
	echo "Doing $i"
	gnuplot -persist <<-EOFMarker
		set term pngcairo
		set output '$i.png'
#		set yrange[0:50000]
		# derivative functions.  Return 1/0 for first point, otherwise delta y or (delta y)/(delta x)
		d(y) = (\$0 == 0) ? (y1 = y, 1/0) : (y2 = y1, y1 = y, y1-y2)
		d2(x,y) = (\$0 == 0) ? (x1 = x, y1 = y, 1/0) : (x2 = x1, x1 = x, y2 = y1, y1 = y, (y1-y2)/(x1-x2))

		set key bottom left Left reverse 

		# offset for derivatives (half the x spacing)
		dx = 0.25

		plot 'mys0$i' u (\$1-dx):(d(\$2))
	EOFMarker
	display "$i.png" &
done
